Dodane nowe opcje
Radio1-7/Radio17bot pull request #2
Opened 2021-05-17 19:43 UTC by Jonitrexis

- Przeniesione funkcje, by zwykłe z prefixem były nad slash, zwiększa to czytelność kodu
- Wszystkie apostrofy zmienione na cudzysłów
- Dodana opcja wysyłania wiadomości na czat przy pomocy API
- Dodana opcja wyświetlania ramówki na dany dzień:
    - Każda audycja wyświetlana na osobnej stronie embeda
    - Każda strona posiada nazwę audycji, ramy godzinowe, zdjęcie audycji i jeśli jest to opis
    - Możliwość wybrania skróconej ramówki, która wyświetla tylko nazwy audycji do końca dnia i ich godziny
- Zmniejszono ilość calli do json( )
- Usunięty komentarz z instalacjami pakietów, zostanie przeniesiony do README
- Dodany ratelimit na zwykłe komendy, 60s
- Ujednolicono nazwy zmiennych na język angielski
- Usuniętno zbędne cudzysłowy

2021-05-18 16:39 UTC, Magiczne requested changes

2021-05-18 16:39 UTC, Magiczne commented on README.md
>  # Radio17bot
O, fajne, podoba mi się. Dokumentacja zawsze spoko

2021-05-18 16:39 UTC, Magiczne commented on main.py
> -#pip install -U discord-py-slash-command PyNaCl potrzebne do bibliotek
Jak chcesz zmień jak nie to nie - zauważyłem że w dużych projektach ludzie robią tak, że najpierw 
`import xxx`

a potem
`from xxx import yyy`

Też tak zacząłem robić, ale to tylko takie zauważenie

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +    except:
Wyjątek będzie spowodowany zawsze przez wysłanie w wiadomości prywatnej, czy może być jeszcze jakiś inny powód?

2021-05-18 16:39 UTC, Magiczne commented on main.py
>  async def cbg(ctx):
Trochę upierdliwość, a trochę *clean code* - nazwa metody `cbg` nie mówi w sumie nic. Zmieniłbym na coś faktycznie mówiącego

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        will_play = json_resp["next"]["artist"] + " - " + json_resp["next"]["title"]
Interpolacja?
```suggestion
        will_play = f'{json_resp["next"]["artist"]} - {json_resp["next"]["title"]}'
```

Jest szybsza niż konkatenacja, ale jeżeli wolisz konkatenację dla czytelności to nie zmieniaj

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        will_play = json_resp["next"]["artist"] + " - " + json_resp["next"]["title"]
Jak wyżej z interpolacją

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +async def _cbg(ctx: SlashContext):
To samo z nazwą

2021-05-18 16:39 UTC, Magiczne commented on main.py
>  async def _cjg(ctx: SlashContext):
To samo z nazwą

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +    is_played = json_resp["current"]["artist"] + " - " + json_resp["current"]["title"]
To samo z interpolacją

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +    message = message[1:]
Bardziej dla czytelności, wypadałoby dodać komentarz czemu robisz `[1:]`.
Czytając to za pare dni już możesz nie pamiętać. Domyślam się że chodzi o usunięcie znaku `/` albo `$`?

2021-05-18 16:39 UTC, Magiczne commented on main.py
>  from discord import FFmpegOpusAudio
Nie myślałeś, żeby ten kod otypować? Wiem, że python i loose-typing, ale jednak typy w kodzie to świetna rzecz.

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +async def cjg(ctx):
To samo z nazwą

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +    is_played = json_resp["current"]["artist"] + " - " + json_resp["current"]["title"]
To samo z interpolacją

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +    is_played = json_resp["current"]["artist"] + " - " + json_resp["current"]["title"]
Może by się to dało do jakiegoś utility-function wyciągnąć, bo w dużej ilości miejsc to jest takie samo.

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        await ctx.send("Twoja wiadomość o treści: \"%s\" została wysłana." % message)
```suggestion
        await ctx.send(f'Twoja wiadomość o treści: "{message}" została wysłana.')
```
Temu ja zazwyczaj stringi daję w apostrofach, bo częściej się zdarzy cudzysłów w stringu niż apostrof.

Ale to nie o tym - jak już interpolujesz w P3, to raczej f-stringiem, szczególnie jak targetujesz pythona 3.8

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        await ctx.send("Twoja wiadomość o treści: \"%s\" została wysłana." % message)
Wyżej też takie jedno było

2021-05-18 16:39 UTC, Magiczne commented on main.py
> -#pip install -U discord-py-slash-command PyNaCl potrzebne do bibliotek
I bardzo mi się podoba ten asynchroniczny kod w pythonie. Fajne to

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +async def schedule(ctx, day):
Przyczepiłbym się do stylu trochę. Długa metoda, wiadomo, musi tak byc, ale nie zaszkodziło by jej trochę white-space. Entery po kluczowych sekcjach np

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        return
```suggestion
        return
        
```

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        return
```suggestion
        return
        
```

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +        pages.append(embed)
```suggestion
        pages.append(embed)
        
```

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +
Przecinek w poprzedniej linii i enter się wkradły

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +async def _schedule(ctx: SlashContext, day: str):
No te same uwagi co do metody wyżej.

2021-05-18 16:39 UTC, Magiczne commented on main.py
> +                               error.retry_after)
```suggestion
        await ctx.channel.send(f'This command is on a {error.retry_after:.2f}s cooldown')
```

Chyba tak, albo %.2f, nie pamiętam bez interpretera przez oczami

2021-05-18 17:00 UTC, Jonitrexis commented on main.py
> +    except:
Hmm, mógłby się pojawić jeśli shoutcast byłby wyłączony i wtedy FFmpegOpusAudio by nie mogło z niego utworzyć źródła dźwięku. Jeśli trzeba, to mogę tam wrzucić jakiegoś kolejnego excepta który by pisał, że radio obecnie jest wyłączone.

2021-05-18 17:01 UTC, Jonitrexis commented on main.py
>  async def cbg(ctx):
Zapytam w sumie przeciętnego użytkownika jak by to mogło się nazywać, by się łatwo używało i zmienię.

2021-05-18 17:06 UTC, Jonitrexis commented on main.py
> +    message = message[1:]
Akurat tu po prostu usuwam spację przed całą wiadomością, dzielę ją na trzy części i zostaje spacja przed samą treścią wiadomości. Ale chyba i tak mam pomysł jak to ładniej rozwiązać bez ``[1:]``.

2021-05-18 17:10 UTC, Jonitrexis commented on main.py
> +    message = message[1:]
Ale ogólnie i tak by się przydało pokomentować cały kod.

2021-05-18 17:15 UTC, Magiczne commented on main.py
> +    except:
Myślę, że warto, bo zdarza się że SHOUTcast się wypieprzy

2021-05-18 17:15 UTC, Magiczne commented on main.py
>  async def cbg(ctx):
W sensie dla usera "Co będzie grane?" jest super.

Ale dla kodu `cbg` już nie.
Jakieś `played_next` albo `what_is_next`, albo coś.

2021-05-18 17:16 UTC, Magiczne commented on main.py
> +    message = message[1:]
Ok, no właśnie widzisz, nie udało się zgadnąć.

Jakby to się na parę plików udało rozbić też by było super, ale to już pewnie ciezej nie?

2021-05-18 17:26 UTC, Jonitrexis commented on main.py
>  async def cbg(ctx):
Tylko niestety dla usera będzie też ``played_next`` jak zmienię nazwę metody, przynajmniej w przypadku komend z prefixami. Mogę dodać alias, że ``cbg`` też będzie działało, a zmienić nazwę metody w kodzie i użytkownik nie będzie miał pojęcia, że używa aliasu.

2021-05-18 17:27 UTC, Jonitrexis commented on main.py
> +    message = message[1:]
Że każdą komendę na przykład na inny plik? Coś tam kojarzę, że jest biblioteka cogs ale bym się musiał wczytać w nią.

2021-05-18 17:30 UTC, Magiczne commented on main.py
>  async def cbg(ctx):
Aa, czyli to tak działa, że nazwa metody w pythonie jest nazwą komendy?

2021-05-18 17:43 UTC, Jonitrexis commented on main.py
>  async def cbg(ctx):
Właśnie w przypadku ``/`` nie ma znaczenia nazwa metody, bo nazwę komendy wybiera się samemu przy pomocy ``name=``. Ale te z prefixem niestety mają taką samą nazwę metody jak nazwa komendy. Mógłbym w teorii pozbyć się całkowicie tych z prefixem, ale większość użytkowników discorda jest jeszcze przyzwyczajonych właśnie do nich.

2021-05-19 12:05 UTC, Jonitrexis commented on main.py
> +    message = message[1:]
Znalazłem bibliotekę do tego, bardzo ładnie działa i nawet z ``/`. Poprawię to co trzeba, a później go przepiszę.

2021-05-21 19:29 UTC, Jonitrexis commented on main.py
>  async def cbg(ctx):
Dobra, jednak znalazłem, da się zmienić nazwę komendy zwykłej też.

2021-05-22 07:36 UTC, Magiczne requested changes

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +bot = commands.Bot(command_prefix="$")  # ustala prefix bota na '$'
Taka bardziej uwaga z cyklu "kod produkcyjny" - ten komentarz jest tu zbędny, nazwa parametru mówi wystarczająco dużo

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +    await bot.change_presence(activity=discord.Game(name="Radio 1.7"))  # zmienia aktywnosc bota na 'Playing Radio 1.7'
Tutaj to samo z komentarzem

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +    if message.author == bot.user:  # ignoruje wiadomosci bota, by bot na swoje same nie odpowiadal
```suggestion
    # ignoruje wiadomości bota, by bot na swoje same nie odpowiadał
    if message.author == bot.user: 
```
Jeżeli już dajesz komentarze to najlepiej nad linią do której jest on przypisany, wszędzie się tak raczej przyjęło. Dlaczego? Jak robisz później zmianę to w historii gita widać że zmieniła się cała linia - jak robisz zmianę tylko komentarza to widać że zmieniłęś komentarz. Stricte pod taki komfort pracy

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +async def on_command_error(ctx, error): # w przypadku gdy komenda jest na cooldownie wysyla wiadomosc ile sekund pozosalo do jej nastepego uzycia
```suggestion
async def on_command_error(ctx, error):
    """W przypadku gdy komenda jest na cooldownie, wysyła wiadomość ile sekund pozostało do jej następnego użycia"""
```

Tu bym zostawił, ale w formie docblocka raczej

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +bot.load_extension('player')  # laduje kolejne rozszerzenia
```suggestion
# Ładowanie rozszerzeń
bot.load_extension('player')
```

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +ListOfCogs = bot.cogs
Czy to przypisanie do zmiennej ma jakiś większy sens za sobą, czy można by niżej dać `bot.cogs.items()` ?

2021-05-22 07:36 UTC, Magiczne commented on main.py
> +for NameOfCog, TheClassOfCog in ListOfCogs.items():     # do debugowania, sprawdza czy wszystkie rozszerzenia sie zaladowaly
Jeżeli mamy coś do debugu, to fajnie by było sobie zdefiniować gdzieś stałą `DEBUG = True` i ustawiać odpowiednio w zależności czy jesteśmy na dev czy na produkcji

2021-05-22 07:36 UTC, Magiczne commented on player.py
> +from discord.ext import commands
O komentarzach w tej samej linii już pisałem, więc jak coś to się powtarzać nie będę, wiesz o co kaman

2021-05-22 07:36 UTC, Magiczne commented on player.py
> +    async def play(self, ctx: commands.Context):
```suggestion
    async def play(self, ctx: commands.Context) -> None:
```
Skoro już część metody otypowana, to można całość

2021-05-22 07:36 UTC, Magiczne commented on player.py
> +            await ctx.send("Miłego słuchania!")
Ten cały fragment jest identyczny jak w tej komendzie wyżej nie?
Myślę że nie teraz, bo chcielibyśmy już zmergować, ale można by to wyciągnąć do jakiejś metody 
```python
from typing import Union

__startPlaying(self, ctx: Union[commands.Context, SlashContext]) -> None
``` 
i ją wywołać w obu miejscach

2021-05-22 07:36 UTC, Magiczne commented on player.py
> +    async def stop(self, ctx):
A tu już ni ma typowania :c

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +week_days = ("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")  #lista dni tygodnia
Komentarz zbędny, i tak z czysto technicznego punktu widzenia to nie jest lista xD

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +        name='cjg'
Cudzysłowy zamiast apostrowów żeby spójnym być. Też w kilku miejscach jest

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +            embed.add_field(name=err, value="https://radio17.pl")
Chyba można zrobić to inline, bo długości linii wynikającej z PEP8 nie przekroczy.
```suggestion
            embed.add_field(name="No nie wiem co będzie grane.", value="https://radio17.pl")

```

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +    async def schedule(self, ctx, day):
I w tej metodzie idealnie widać czemu komentarze linię wyżej.
Rozciągnęło się okropnie, długości linii PEP8 na pewno nie spełnia i trzeba skrolować żeby przeczytać komentarz

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +        resp = requests.get("https://radio17.pl/api/stream/stats/extended")  # zapytanie do API o to co bedzie grane
Wciąż się zastanawiam, czy nie byłoby lepiej wyciągnąć wszystkich urli do api do jakiegoś osobnego modułu w którym będą tylko one, i sobie importować

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +            try:
```suggestion
                await message.edit(embed=pages[i])
                
            try:
```
Żeby oddzielić dwa logiczne bloki robiące co innego

https://dev.to/suckup_de/do-not-fear-the-white-space-in-your-code-39d0

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +        resp = requests.get("https://radio17.pl/api/schedule")
```suggestion
            return
            
        resp = requests.get("https://radio17.pl/api/schedule")

```

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +                if int(broadcast["end_hour"][:2]) > datetime.datetime.today().hour:
```
# Jakiś komentarz do tego czemu [:2], wyżej to gdzieś było, ale tutaj też się przyda, gdyby czytać tylko tą metodę
if int(broadcast["end_hour"][:2]) > datetime.datetime.today().hour:
```

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +                                          value=broadcast["start_hour"] + " - " + broadcast["end_hour"], inline=False)
W innym pliku był f-string, to tu też można

2021-05-22 07:36 UTC, Magiczne commented on schedule_info.py
> +        await message.add_reaction('⏭')
I kolejna rozkmina - emoji nie wprowadza się tak łatwo z klawiatury, jak zwykłego tekstu, może też jakieś stałe w klasie, do których się tylko będziemy odwoływać?

2021-05-22 07:36 UTC, Magiczne commented on sending_messages.py
> +        msg = {"author": author, "content": ' '.join(message)}
Tutaj się zastanawiam, czy jest jakaś możliwość walidacji długości wiadomości w discordowym api?
Bo chat nie puści wiadomości dłuższej niż **chyba** 150 znaków, trzeba by zerknąć w kod albo na stronę.

2021-05-22 07:40 UTC, Magiczne commented on main.py
> +for NameOfCog, TheClassOfCog in ListOfCogs.items():     # do debugowania, sprawdza czy wszystkie rozszerzenia sie zaladowaly
Można nawet `.env` wykorzystać 
https://pypi.org/project/python-dotenv/

2021-05-22 07:41 UTC, Magiczne commented on schedule_info.py
> +        resp = requests.get("https://radio17.pl/api/stream/stats/extended")  # zapytanie do API o to co bedzie grane
Ale to bardziej do poddania pod dyskusję

2021-05-22 13:47 UTC, Jonitrexis commented on sending_messages.py
> +        msg = {"author": author, "content": ' '.join(message)}
Jak spojrzałem na docsy, to za bardzo nie ma i jako przykład jest pokazane używanie zwykłego ``len`` pythonowego: ``len(ctx.message.content)``.

2021-05-22 13:48 UTC, Jonitrexis commented on schedule_info.py
> +        await message.add_reaction('⏭')
Można, albo mógłbym je zamienić na unicode.

2021-05-22 13:49 UTC, Jonitrexis commented on schedule_info.py
> +                                          value=broadcast["start_hour"] + " - " + broadcast["end_hour"], inline=False)
A rzeczywiście, musiało mi umknąć.

2021-05-22 13:53 UTC, Jonitrexis commented on main.py
> +bot = commands.Bot(command_prefix="$")  # ustala prefix bota na '$'
Właśnie z komentarzami mam problem, bo teraz na świeżo wiem co jest co i nie do końca wiem gdzie komentarze wrzucić. Jakby ci się chciało później, to możesz dodać gdzie jeszcze coś by wypadało skomentować.

2021-05-22 14:37 UTC, Jonitrexis commented on schedule_info.py
> +        resp = requests.get("https://radio17.pl/api/stream/stats/extended")  # zapytanie do API o to co bedzie grane
W zasadzie można. A tak przy okazji to czytając docsy znalazłem, że bibliotekę ``requests`` lepiej zastąpić asynchroniczną ``aiohttp`` .

2021-05-22 15:37 UTC, Magiczne commented on main.py
> +bot = commands.Bot(command_prefix="$")  # ustala prefix bota na '$'
Jasne mogę jak najbardziej tylko myślę że jak rozwiążesz wszystkie komentarze do tej pory bo się tego najebali XD

2021-05-22 15:38 UTC, Magiczne commented on schedule_info.py
> +        resp = requests.get("https://radio17.pl/api/stream/stats/extended")  # zapytanie do API o to co bedzie grane
Z http nie miałem w pythonie styczności dużo. Głównie ML i Django. Calli po http nie robiłem. 

Ale wygląda na fajna libke, możesz dodać issue że by podmienić :D

2021-05-22 15:39 UTC, Magiczne commented on schedule_info.py
> +        await message.add_reaction('⏭')
Imho lepiej Emoji już. 
Plik i tak zapisany w Unicode

I.od razu wiesz co to

2021-05-22 15:40 UTC, Magiczne commented on sending_messages.py
> +        msg = {"author": author, "content": ' '.join(message)}
Api niby rzuci błędy ale to trzeba by je obsłużyć, a można walidowac już przed tym jak do API poleci

2021-05-22 16:02 UTC, Jonitrexis commented on main.py
> -#pip install -U discord-py-slash-command PyNaCl potrzebne do bibliotek
Co do tych importów, to Pycharm mi je podkreśla jeśli je w taki sposób robię.

2021-05-22 16:03 UTC, Jonitrexis commented on main.py
> +ListOfCogs = bot.cogs
Można, się poprawi.

2021-05-22 16:05 UTC, Jonitrexis commented on sending_messages.py
> +        msg = {"author": author, "content": ' '.join(message)}
To się dorzuci jakieś "Twoja wiadomość jest za długa, limit wynosi 150 znaków.".

2021-05-22 16:54 UTC, Magiczne commented on main.py
> -#pip install -U discord-py-slash-command PyNaCl potrzebne do bibliotek
No to chrzanić.

2021-05-22 18:45 UTC, Magiczne commented on README.md
> +Przed stworzeniem swojej instancji bota trzeba zainstalować biblioteki ``PyNaCl`` oraz ``discord-py-slash-command`` oraz utworzenie pliku ``.env`` i podanie tam unikalnego tokenu bota oraz ustawienie
true z małej litery? czy false z dużej? któreś xD

2021-05-22 18:45 UTC, Magiczne commented on README.md
> +Przed stworzeniem swojej instancji bota trzeba zainstalować biblioteki ``PyNaCl`` oraz ``discord-py-slash-command`` oraz utworzenie pliku ``.env`` i podanie tam unikalnego tokenu bota oraz ustawienie
A, widzę w kodzie że więcej możliwych wartości jest. Ale to w docu można sprecyzować jeden konkretny i w kodzie też

2021-05-22 18:45 UTC, Magiczne commented on main.py
> +    # ignoruje wiadomosci bota, by bot na swoje same nie odpowiadal
W sumie to czemu polskie znaki z komentarzy usuwasz?

2021-05-22 18:55 UTC, Jonitrexis commented on main.py
> +    # ignoruje wiadomosci bota, by bot na swoje same nie odpowiadal
Czasem się zdarzy, że jakiś skrót klawiszowy z Pycharma koliduje z skrótem do polskiego znaku to przepisując pominąłem znaki, mogę dodać.

2021-05-22 19:07 UTC, Magiczne commented on main.py
> +    # ignoruje wiadomosci bota, by bot na swoje same nie odpowiadal
Myśle że jak już po polsku to z polskimi znakami, albo po angielsku xD

2021-05-22 19:09 UTC, Magiczne commented on main.py
> +    # ignoruje wiadomosci bota, by bot na swoje same nie odpowiadal
Z tipów, polskie znaki można tworzyć z tyldą.

Tylda + litera = polski znak

2021-05-22 19:29 UTC, Jonitrexis commented on main.py
> +    # ignoruje wiadomosci bota, by bot na swoje same nie odpowiadal
O, to z tyldą się przyda. Bo na przykład przy tworzeniu "Ł" odpala się skrót do reformatowania pliku.

2021-05-22 20:40 UTC, Magiczne approved these changes

2021-05-22 20:41 UTC, merged